# Generated by Django 5.0.1 on 2024-01-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_employee_branch_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
